// Cloud Messaging API (Legacy)
POST  https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key=AAAAov9u7B0:APA91bE97hrUlk46aAucfu7hTBNKf_IdrS6LNa-SUmTBp6N4tJtE42fx3Zduu0eUyS8B1y1zRhRdrFa-Ur24RZVVkU8Ax_Ry4OnV89HzaYJgjRz-ZWSlCQ86JQTc_18Ec_rsMj4GDBpA

{
    "registration_ids": ["getToken()"],
    // "to":"VALID_REGISTRATION_ID",

    "data": {
        "title": "Title",
        "body": "message",
        "image": "...",
    }
}

###

// FCM REST API v1
POST https://fcm.googleapis.com/v1/projects/calendar-activities/messages:send
# POST https://fcm.googleapis.com/v1/projects/700070161437/messages:send
Content-Type: application/json
Authorization: Bearer oauth2-access-token

{
    "message": {
        "token": "XXX",
        "notification": {
            "title": "Title",
            "body": "message",
            "image": "...",
        },
        "data": {
            "key1": "value1",
            "key2": "value2"
        }

    }
}